let products = [
  {
    name: "Bolsa Professora Com Repartições",
    tag: "b1000",
    price: 170,
    inCart: 0,
  },
  {
    name: "Necessaires Tamanho P",
    tag: "n1000",
    price: 15,
    inCart: 0,
  },
  {
    name: "Estojo Um Compartimento Branco",
    tag: "e1000",
    price: 25,
    inCart: 0,
  },
  {
    name: "Bolsa Professora Com Repartições",
    tag: "b1001",
    price: 170,
    inCart: 0,
  },
  {
    name: "Lancheira Térmica",
    tag: "l1000",
    price: 95,
    inCart: 0,
  },
  {
    name: "Estojo Miney Um Compartimento Vermelho",
    tag: "e1001",
    price: 25,
    inCart: 0,
  },
  {
    name: "Estojo Mickey Um Compartimento Branco",
    tag: "e1002",
    price: 25,
    inCart: 0,
  },
  {
    name: "Estojo Mickey Um Compartimento Azul",
    tag: "e1003",
    price: 25,
    inCart: 0,
  },
  {
    name: "Mochila Mickey - Bolso 3D Tamanho Grande",
    tag: "m1000",
    price: 250,
    inCart: 0,
  },
  {
    name: "Necessaire Estampa Mandala",
    tag: "n1001",
    price: 25,
    inCart: 0,
  },
  {
    name: "Necessaire Estampa Flamingo",
    tag: "n1002",
    price: 35,
    inCart: 0,
  },
  {
    name: "Necessaire Com Forro Impermeavél",
    tag: "n1003",
    price: 50,
    inCart: 0,
  },
  {
    name: "Necessaire Tecido Sintético",
    tag: "n1004",
    price: 20,
    inCart: 0,
  },
  {
    name: "Estojo Um Compartimento Tecido Sintético",
    tag: "e1004",
    price: 20,
    inCart: 0,
  },
  {
    name: "Necessaire Multiuso",
    tag: "n1005",
    price: 35,
    inCart: 0,
  },
  {
    name: "Necessaire Animal Print Sintético",
    tag: "n1006",
    price: 35,
    inCart: 0,
  },
];